{"name": "test_update_user_data_without_auth_should_fail", "status": "passed", "description": "Тест для попытки обновления данных пользователя без авторизации", "start": 1744991683597, "stop": 1744991683691, "uuid": "836c5044-b7f8-4539-9965-ec6e82ca9076", "historyId": "436ec232415d08f5184a9a5c55ddaa51", "testCaseId": "436ec232415d08f5184a9a5c55ddaa51", "fullName": "tests.test_user_update#test_update_user_data_without_auth_should_fail", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user_update"}, {"name": "subSuite", "value": "TestUserUpdate"}, {"name": "host", "value": "DESKTOP-U9HTL48"}, {"name": "thread", "value": "39648-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_update"}]}