{"name": "test_update_user_data_invalid_field", "status": "failed", "statusDetails": {"message": "AssertionError: assert 403 == 200\n  +403\n  -200", "trace": "api_client = <utils.api_client.APIClient object at 0x00000182FE961E50>\nuser_data = {'email': 'testuser@example.com', 'name': 'Test User', 'password': 'password123'}\n\n    @pytest.fixture(scope=\"session\")\n    def ensure_user_created(api_client, user_data):\n        \"\"\"Фикстура для регистрации пользователя\"\"\"\n        response = api_client.register_user(user_data)\n>       assert response.status_code == 200\nE       assert 403 == 200\nE         +403\nE         -200\n\ntests\\conftest.py:26: AssertionError"}, "description": "Тест для обновления данных с невалидным полем", "start": 1744991683701, "stop": 1744991683701, "uuid": "7a90bc45-69d5-4d3c-9527-1049791c2caa", "historyId": "e95a950f64e1265751f79a8bae2ed1b4", "testCaseId": "e95a950f64e1265751f79a8bae2ed1b4", "fullName": "tests.test_user_update#test_update_user_data_invalid_field", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user_update"}, {"name": "subSuite", "value": "TestUserUpdate"}, {"name": "host", "value": "DESKTOP-U9HTL48"}, {"name": "thread", "value": "39648-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_update"}]}