{"name": "test_login_with_invalid_credentials", "status": "passed", "description": "Тест для авторизации с неверными данными пользователя", "start": 1744991683063, "stop": 1744991683161, "uuid": "4cb5681e-d224-40e7-ab3d-eab03ecae1f8", "historyId": "7cc77bdf9c8f82a4c10d09af5131748e", "testCaseId": "7cc77bdf9c8f82a4c10d09af5131748e", "fullName": "tests.test_login#test_login_with_invalid_credentials", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-U9HTL48"}, {"name": "thread", "value": "39648-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}